# Generated by Django 4.2.11 on 2026-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0035_publicaccountrequest_account_type_and_user_fields'),
        ('contacts', '0004_alter_contact_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='destinations',
            field=models.ManyToManyField(blank=True, help_text='Laisser vide pour toutes les destinations.', related_name='contacts_scoped', to='wms.destination'),
        ),
    ]
