# Generated by Django 4.2.11 on 2026-02-18

from django.db import migrations


def backfill_destinations_from_legacy_field(apps, schema_editor):
    Contact = apps.get_model("contacts", "Contact")
    through = Contact.destinations.through
    existing_pairs = set(through.objects.values_list("contact_id", "destination_id"))
    links = []

    for contact in Contact.objects.exclude(destination_id__isnull=True).iterator():
        pair = (contact.id, contact.destination_id)
        if pair in existing_pairs:
            continue
        links.append(
            through(
                contact_id=contact.id,
                destination_id=contact.destination_id,
            )
        )

    if links:
        through.objects.bulk_create(links, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contact_destinations"),
    ]

    operations = [
        migrations.RunPython(
            backfill_destinations_from_legacy_field,
            reverse_code=noop_reverse,
        ),
    ]
