# Generated by Django 4.2.11 on 2026-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_backfill_contact_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linked_shippers',
            field=models.ManyToManyField(blank=True, help_text='Utilise pour les destinataires: vide = tous les expéditeurs.', related_name='linked_recipients', symmetrical=False, to='contacts.contact'),
        ),
    ]
