# Generated by Django 5.2.12 on 2026-03-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linked_shippers',
        ),
        migrations.DeleteModel(
            name='ContactTag',
        ),
    ]
