# Generated by Django 5.2.12 on 2026-03-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_remove_contact_tags_remove_contact_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("donor", "Donateur"),
                            ("transporter", "Transporteur"),
                            ("volunteer", "Benevole"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["contact__name", "capability"],
            },
        ),
        migrations.AddConstraint(
            model_name="contactcapability",
            constraint=models.UniqueConstraint(
                fields=("contact", "capability"),
                name="contacts_capability_unique_per_contact_type",
            ),
        ),
        migrations.AddIndex(
            model_name="contactcapability",
            index=models.Index(
                fields=["capability", "is_active"],
                name="contacts_capability_lookup_idx",
            ),
        ),
    ]
