# Generated by Django 5.2.12 on 2026-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contactcapability'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='beneficiary_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('association', 'Association'), ('private_sector', 'Secteur privé'), ('public_sector', 'Publique'), ('other', 'Autre')], max_length=30),
        ),
    ]
