# Generated by Django 5.2.12 on 2026-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0010_contact_beneficiary_count_contact_legal_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("donor", "Donateur"),
                    ("transporter", "Transporteur"),
                    ("volunteer", "Benevole"),
                    ("partner", "Partenaire"),
                    ("other", "Autre"),
                ],
                max_length=40,
            ),
        ),
    ]
