# Generated by Django 5.2.12 on 2026-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contactcapability_partner_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_humanitarian_attestation_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
