# Generated by Django 4.2.11 on 2025-12-21 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('shipped', 'Shipped')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=40)),
                ('aisle', models.CharField(max_length=40)),
                ('shelf', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['warehouse', 'zone', 'aisle', 'shelf'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_g', models.IntegerField(blank=True, null=True)),
                ('volume_cm3', models.IntegerField(blank=True, null=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=200)),
                ('perishable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, max_length=80)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('quarantined', 'Quarantined'), ('available', 'Available'), ('hold', 'Hold'), ('expired', 'Expired')], default='available', max_length=20)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('storage_conditions', models.CharField(blank=True, max_length=200)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'expires_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('picking', 'Picking'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('shipper_name', models.CharField(max_length=200)),
                ('shipper_contact', models.CharField(blank=True, max_length=200)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_contact', models.CharField(blank=True, max_length=200)),
                ('destination_address', models.TextField()),
                ('destination_country', models.CharField(default='France', max_length=80)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('transfer', 'Transfer'), ('adjust', 'Adjust'), ('precondition', 'Precondition'), ('unpack', 'Unpack')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('reason_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_from', to='wms.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product')),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.productlot')),
                ('related_carton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.carton')),
                ('related_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.shipment')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_to', to='wms.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wms.productcategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='wms.producttag'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehouse'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('donation_certificate', 'Donation certificate'), ('humanitarian_certificate', 'Humanitarian certificate'), ('customs', 'Customs'), ('shipment_note', 'Shipment note'), ('packing_list_carton', 'Packing list carton'), ('packing_list_shipment', 'Packing list shipment')], max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.shipment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='carton',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wms.location'),
        ),
        migrations.AddField(
            model_name='carton',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carton',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.shipment'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'zone', 'aisle', 'shelf')},
        ),
        migrations.CreateModel(
            name='CartonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.carton')),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.productlot')),
            ],
            options={
                'unique_together': {('carton', 'product_lot')},
            },
        ),
    ]
