# Generated by Django 4.2.11 on 2025-12-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='wms.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='quarantine_default',
            field=models.BooleanField(default=False),
        ),
    ]
