# Generated by Django 4.2.11 on 2025-12-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_product_default_location_product_quarantine_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
