# Generated by Django 4.2.11 on 2025-12-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_product_is_active_product_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
