# Generated by Django 4.2.11 on 2025-12-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='correspondent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
