# Generated by Django 4.2.11 on 2025-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_shipment_correspondent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reference',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
