# Generated by Django 4.2.11 on 2025-12-22 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('wms', '0008_receipt_alter_cartonformat_height_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('shipper_name', models.CharField(max_length=200)),
                ('recipient_name', models.CharField(max_length=200)),
                ('correspondent_name', models.CharField(blank=True, max_length=200)),
                ('destination_address', models.TextField()),
                ('destination_city', models.CharField(blank=True, max_length=120)),
                ('destination_country', models.CharField(default='France', max_length=80)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('correspondent_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_correspondent', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recipient_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_recipient', to='contacts.contact')),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='wms.shipment')),
                ('shipper_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_shipper', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reserved_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prepared_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.product')),
            ],
            options={
                'ordering': ['order', 'product'],
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='productlot',
            name='quantity_reserved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='wms.orderline')),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.productlot')),
            ],
            options={
                'ordering': ['order_line', 'product_lot'],
            },
        ),
    ]
