# Generated by Django 4.2.11 on 2025-12-23 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('wms', '0009_order_orderline_productlot_quantity_reserved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transport_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptDonorSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
            ],
            options={
                'ordering': ['year', 'donor__name'],
                'unique_together': {('year', 'donor')},
            },
        ),
    ]
