# Generated by Django 4.2.11 on 2025-12-23 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_receiptsequence_receipt_pallet_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='carton_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='receipt',
            name='hors_format_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('pallet', 'Pallet'), ('association', 'Association'), ('other', 'Other')], default='donation', max_length=20),
        ),
        migrations.CreateModel(
            name='ReceiptHorsFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hors_format_items', to='wms.receipt')),
            ],
            options={
                'ordering': ['receipt', 'line_number'],
                'unique_together': {('receipt', 'line_number')},
            },
        ),
    ]
