# Generated by Django 4.2.11 on 2025-12-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_receipt_carton_count_receipt_hors_format_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlot',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_lots', to='wms.receipt'),
        ),
    ]
