# Generated by Django 4.2.11 on 2025-12-23 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0012_productlot_source_receipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="WmsChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("last_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
