# Generated by Django 4.2.11 on 2025-12-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0013_wmschange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=120)),
                ("iata_code", models.CharField(max_length=10, unique=True)),
                ("country", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "correspondent_contact",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="destinations_as_correspondent", to="contacts.contact"),
                ),
            ],
            options={
                "ordering": ["city"],
                "unique_together": {("city", "country")},
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="shipments", to="wms.destination"),
        ),
    ]
