# Generated by Django 4.2.11 on 2025-12-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0014_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
