# Generated by Django 4.2.11 on 2025-12-24 19:12

from django.db import migrations, models


def forwards(apps, schema_editor):
    Carton = apps.get_model("wms", "Carton")
    Carton.objects.filter(status="ready").update(status="packed")
    Carton.objects.filter(status="assigned").update(status="packed")


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0015_shipment_ready_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carton",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Cree"),
                    ("picking", "En preparation"),
                    ("packed", "Pret"),
                    ("shipped", "Expedie"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
