# Generated by Django 4.2.11 on 2025-12-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0016_carton_status_pack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("donation_certificate", "Donation certificate"),
                    ("humanitarian_certificate", "Humanitarian certificate"),
                    ("customs", "Customs"),
                    ("shipment_note", "Shipment note"),
                    ("packing_list_carton", "Packing list carton"),
                    ("packing_list_shipment", "Packing list shipment"),
                    ("additional", "Document additionnel"),
                ],
                max_length=40,
            ),
        ),
    ]
