# Generated by Codex on 2026-01-16
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0031_rename_wms_integr_direction_8f4b55_wms_integra_directi_b3fd24_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ean",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="product",
            name="pu_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tva",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="TVA en taux (ex: 0.2 pour 20%).",
                max_digits=6,
                null=True,
                validators=[MinValueValidator(Decimal("0.0000"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pu_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=10,
                null=True,
            ),
        ),
    ]
