# Generated by Django 4.2.11 on 2026-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0033_shipment_tracking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
