# Generated by Django 4.2.11 on 2026-02-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        ('wms', '0035_publicaccountrequest_account_type_and_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='correspondent_contact_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_correspondent', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_contact_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_recipient', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_contact_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_shipper', to='contacts.contact'),
        ),
    ]
