# Generated by Django 4.2.11 on 2026-02-18 19:57

from django.db import migrations, models


def mark_linked_cartons_as_assigned(apps, schema_editor):
    Carton = apps.get_model("wms", "Carton")
    Carton.objects.filter(
        shipment_id__isnull=False,
        status__in=["draft", "picking", "packed"],
    ).update(status="assigned")


def revert_assigned_cartons_to_packed(apps, schema_editor):
    Carton = apps.get_model("wms", "Carton")
    Carton.objects.filter(
        shipment_id__isnull=False,
        status="assigned",
    ).update(status="packed")


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0036_shipment_correspondent_contact_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carton',
            name='status',
            field=models.CharField(choices=[('draft', 'Cree'), ('picking', 'En preparation'), ('packed', 'Pret'), ('assigned', 'Affecte'), ('labeled', 'Etiquette'), ('shipped', 'Expedie')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Creation'), ('picking', 'En cours'), ('packed', 'Pret'), ('planned', 'Planifie'), ('shipped', 'Expedie'), ('received_correspondent', 'Recu escale'), ('delivered', 'Livre')], default='draft', max_length=30),
        ),
        migrations.RunPython(
            mark_linked_cartons_as_assigned,
            reverse_code=revert_assigned_cartons_to_packed,
        ),
    ]
