# Generated by Django 4.2.11 on 2026-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0037_shipment_disputed_at_shipment_is_disputed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
