# Generated by Django 4.2.11 on 2026-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0044_associationrecipient_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carton',
            name='status',
            field=models.CharField(choices=[('draft', 'Créé'), ('picking', 'En préparation'), ('packed', 'Prêt'), ('assigned', 'Affecté'), ('labeled', 'Étiqueté'), ('shipped', 'Expédié')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartonstatusevent',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Créé'), ('picking', 'En préparation'), ('packed', 'Prêt'), ('assigned', 'Affecté'), ('labeled', 'Étiqueté'), ('shipped', 'Expédié')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartonstatusevent',
            name='previous_status',
            field=models.CharField(choices=[('draft', 'Créé'), ('picking', 'En préparation'), ('packed', 'Prêt'), ('assigned', 'Affecté'), ('labeled', 'Étiqueté'), ('shipped', 'Expédié')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Création'), ('picking', 'En cours'), ('packed', 'Prêt'), ('planned', 'Planifié'), ('shipped', 'Expédié'), ('received_correspondent', 'Reçu escale'), ('delivered', 'Livré')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmenttrackingevent',
            name='status',
            field=models.CharField(choices=[('planning_ok', 'OK pour planification'), ('planned', 'Planifié'), ('moved_export', 'Déplacé au magasin export'), ('boarding_ok', 'OK mise à bord'), ('received_correspondent', 'Reçu correspondant'), ('received_recipient', 'Reçu destinataire')], max_length=40),
        ),
    ]
