# Generated by Django 4.2.11 on 2026-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0047_portal_shipper_scope_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationportalcontact',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'M.'), ('mrs', 'Mme'), ('ms', 'Mlle'), ('dr', 'Dr'), ('pr', 'Pr'), ('pere', 'Père'), ('soeur', 'Sœur'), ('frere', 'Frère'), ('abbe', 'Abbé'), ('imam', 'Imam'), ('rabbin', 'Rabbin'), ('pasteur', 'Pasteur'), ('eveque', 'Évêque'), ('mons', 'Monseigneur'), ('president', 'Président'), ('ministre', 'Ministre'), ('ambassad', 'Ambassadeur'), ('maire', 'Maire'), ('prefet', 'Préfet'), ('gouvern', 'Gouverneur'), ('depute', 'Député'), ('senateur', 'Sénateur'), ('gen', 'Général'), ('colonel', 'Colonel'), ('cmdt', 'Commandant'), ('cpt', 'Capitaine'), ('lt', 'Lieutenant'), ('adj', 'Adjudant'), ('sgt', 'Sergent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='associationrecipient',
            name='contact_title',
            field=models.CharField(blank=True, choices=[('mr', 'M.'), ('mrs', 'Mme'), ('ms', 'Mlle'), ('dr', 'Dr'), ('pr', 'Pr'), ('pere', 'Père'), ('soeur', 'Sœur'), ('frere', 'Frère'), ('abbe', 'Abbé'), ('imam', 'Imam'), ('rabbin', 'Rabbin'), ('pasteur', 'Pasteur'), ('eveque', 'Évêque'), ('mons', 'Monseigneur'), ('president', 'Président'), ('ministre', 'Ministre'), ('ambassad', 'Ambassadeur'), ('maire', 'Maire'), ('prefet', 'Préfet'), ('gouvern', 'Gouverneur'), ('depute', 'Député'), ('senateur', 'Sénateur'), ('gen', 'Général'), ('colonel', 'Colonel'), ('cmdt', 'Commandant'), ('cpt', 'Capitaine'), ('lt', 'Lieutenant'), ('adj', 'Adjudant'), ('sgt', 'Sergent')], max_length=10),
        ),
    ]
