# Generated by Django 4.2.11 on 2026-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0048_alter_associationportalcontact_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
