# Generated by Django 4.2.11 on 2026-02-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0049_order_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsRuntimeSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=20)),
                ('tracking_alert_hours', models.PositiveIntegerField(default=72)),
                ('workflow_blockage_hours', models.PositiveIntegerField(default=72)),
                ('stale_drafts_age_days', models.PositiveIntegerField(default=30)),
                ('email_queue_max_attempts', models.PositiveIntegerField(default=5)),
                ('email_queue_retry_base_seconds', models.PositiveIntegerField(default=60)),
                ('email_queue_retry_max_seconds', models.PositiveIntegerField(default=3600)),
                ('email_queue_processing_timeout_seconds', models.PositiveIntegerField(default=900)),
                ('enable_shipment_track_legacy', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_runtime_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres runtime WMS',
                'verbose_name_plural': 'Paramètres runtime WMS',
            },
        ),
    ]
