# Generated by Django 4.2.11 on 2026-02-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0050_wmsruntimesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsRuntimeSettingsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_runtime_settings_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='wms.wmsruntimesettings')),
            ],
            options={
                'verbose_name': 'Historique parametres runtime WMS',
                'verbose_name_plural': 'Historique parametres runtime WMS',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
