# Generated by Django 4.2.11 on 2026-02-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0053_notification_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUiPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_mode', models.CharField(choices=[('legacy', 'Legacy'), ('next', 'Next')], default='legacy', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wms_ui_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preference interface utilisateur',
                'verbose_name_plural': 'Preferences interface utilisateur',
                'ordering': ['user_id'],
            },
        ),
    ]
