# Generated by Django 4.2.11 on 2026-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0055_wmsruntimesettings_design_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='design_font_h1',
            field=models.CharField(default='DM Sans', max_length=120),
        ),
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='design_font_h2',
            field=models.CharField(default='DM Sans', max_length=120),
        ),
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='design_font_h3',
            field=models.CharField(default='DM Sans', max_length=120),
        ),
    ]
