# Generated by Django 4.2.11 on 2026-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0056_wmsruntimesettings_design_font_h1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmsruntimesettings",
            name="scan_bootstrap_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
