# Generated by Django 4.2.11 on 2026-02-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0057_wmsruntimesettings_scan_bootstrap_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmsruntimesettings",
            name="design_tokens",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
