# Generated by Django 4.2.11 on 2026-02-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0058_wmsruntimesettings_design_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='design_custom_presets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='design_selected_preset',
            field=models.CharField(default='wms-default', max_length=64),
        ),
    ]
