# Generated by Django 4.2.11 on 2026-03-01 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0059_wmsruntimesettings_design_custom_presets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPrintArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_code', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_prints/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onedrive_path', models.CharField(blank=True, max_length=500)),
                ('sync_attempts', models.PositiveIntegerField(default=0)),
                ('last_sync_error', models.TextField(blank=True)),
                ('carton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_print_artifacts', to='wms.carton')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_print_artifacts', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_print_artifacts', to='wms.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('default_page_format', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=4)),
                ('fallback_page_format', models.CharField(blank=True, choices=[('A4', 'A4'), ('A5', 'A5')], max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PrintPackDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=60)),
                ('variant', models.CharField(blank=True, default='', max_length=40)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('xlsx_template_file', models.FileField(blank=True, null=True, upload_to='print_pack_templates/')),
                ('enabled', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wms.printpack')),
            ],
            options={
                'ordering': ['pack__code', 'sequence', 'id'],
                'unique_together': {('pack', 'doc_type', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedPrintArtifactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=60)),
                ('variant', models.CharField(blank=True, default='', max_length=40)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('source_xlsx_file', models.FileField(blank=True, null=True, upload_to='generated_prints/source_xlsx/')),
                ('generated_pdf_file', models.FileField(blank=True, null=True, upload_to='generated_prints/items/')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.generatedprintartifact')),
            ],
            options={
                'ordering': ['artifact__id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrintCellMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksheet_name', models.CharField(max_length=120)),
                ('cell_ref', models.CharField(max_length=16)),
                ('source_key', models.CharField(max_length=200)),
                ('transform', models.CharField(blank=True, max_length=80)),
                ('required', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('pack_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_mappings', to='wms.printpackdocument')),
            ],
            options={
                'ordering': ['pack_document__id', 'sequence', 'id'],
                'unique_together': {('pack_document', 'worksheet_name', 'cell_ref')},
            },
        ),
    ]
