# Generated by Django 4.2.11 on 2026-03-03 10:00

from django.db import migrations, models


def enable_bootstrap_for_existing_runtime_settings(apps, schema_editor):
    WmsRuntimeSettings = apps.get_model("wms", "WmsRuntimeSettings")
    WmsRuntimeSettings.objects.update(scan_bootstrap_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0065_printpackdocumentversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wmsruntimesettings",
            name="scan_bootstrap_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            enable_bootstrap_for_existing_runtime_settings,
            migrations.RunPython.noop,
        ),
    ]
