# Generated by Django 4.2.11 on 2026-03-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        ('wms', '0066_enable_bootstrap_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'M.'), ('mrs', 'Mme'), ('ms', 'Mlle'), ('dr', 'Dr'), ('pr', 'Pr'), ('pere', 'Père'), ('soeur', 'Sœur'), ('frere', 'Frère'), ('abbe', 'Abbé'), ('imam', 'Imam'), ('rabbin', 'Rabbin'), ('pasteur', 'Pasteur'), ('eveque', 'Évêque'), ('mons', 'Monseigneur'), ('president', 'Président'), ('ministre', 'Ministre'), ('ambassad', 'Ambassadeur'), ('maire', 'Maire'), ('prefet', 'Préfet'), ('gouvern', 'Gouverneur'), ('depute', 'Député'), ('senateur', 'Sénateur'), ('gen', 'Général'), ('colonel', 'Colonel'), ('cmdt', 'Commandant'), ('cpt', 'Capitaine'), ('lt', 'Lieutenant'), ('adj', 'Adjudant'), ('sgt', 'Sergent')], max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_contacts', to='contacts.contact')),
            ],
            options={
                'ordering': ['organization__name', 'last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper', 'Expéditeur'), ('recipient', 'Destinataire'), ('correspondent', 'Correspondant'), ('donor', 'Donateur'), ('transporter', 'Transporteur')], max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_role_assignments', to='contacts.contact')),
            ],
            options={
                'ordering': ['organization__name', 'role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='wms.organizationcontact')),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_contacts', to='wms.organizationroleassignment')),
            ],
            options={
                'ordering': ['role_assignment', '-is_primary', 'contact__last_name', 'contact__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationrolecontact',
            constraint=models.UniqueConstraint(fields=('role_assignment', 'contact'), name='wms_org_role_contact_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='organizationrolecontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('role_assignment',), name='wms_org_role_contact_single_primary'),
        ),
        migrations.AddConstraint(
            model_name='organizationroleassignment',
            constraint=models.UniqueConstraint(fields=('organization', 'role'), name='wms_org_role_assignment_unique'),
        ),
    ]
