# Generated by Django 4.2.11 on 2026-03-04 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        ('wms', '0067_organizationcontact_organizationroleassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_destinations', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipper_scopes', to='wms.destination')),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_scopes', to='wms.organizationroleassignment')),
            ],
            options={
                'ordering': ['role_assignment__organization__name', 'role_assignment__id', '-all_destinations', 'destination__city', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipientBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_bindings', to='wms.destination')),
                ('recipient_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_bindings_as_recipient', to='contacts.contact')),
                ('shipper_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_bindings_as_shipper', to='contacts.contact')),
            ],
            options={
                'ordering': ['recipient_org__name', 'shipper_org__name', 'destination__city', '-valid_from', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shipperscope',
            constraint=models.UniqueConstraint(fields=('role_assignment', 'destination'), name='wms_shipper_scope_unique_assignment_destination'),
        ),
        migrations.AddConstraint(
            model_name='shipperscope',
            constraint=models.UniqueConstraint(condition=models.Q(('all_destinations', True), ('is_active', True)), fields=('role_assignment',), name='wms_shipper_scope_single_active_global'),
        ),
        migrations.AddConstraint(
            model_name='recipientbinding',
            constraint=models.UniqueConstraint(fields=('shipper_org', 'recipient_org', 'destination', 'valid_from'), name='wms_recipient_binding_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='recipientbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shipper_org', 'recipient_org', 'destination'), name='wms_recipient_binding_single_active'),
        ),
    ]
