# Generated by Django 4.2.11 on 2026-03-04 10:54

from django import VERSION as DJANGO_VERSION
from django.db import migrations, models
import django.db.models.deletion


def _check_constraint_compat(*, condition, name):
    constraint_kwargs = {"name": name}
    if DJANGO_VERSION >= (5, 1):
        constraint_kwargs["condition"] = condition
    else:
        constraint_kwargs["check"] = condition
    return models.CheckConstraint(**constraint_kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        ('wms', '0068_shipperscope_recipientbinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCorrespondentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspondent_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_correspondent_overrides', to='contacts.contact')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_correspondent_overrides', to='wms.destination')),
                ('recipient_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_correspondent_overrides_as_recipient', to='contacts.contact')),
                ('shipper_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_correspondent_overrides_as_shipper', to='contacts.contact')),
            ],
            options={
                'ordering': ['destination__city', 'correspondent_org__name', 'shipper_org__name', 'recipient_org__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DestinationCorrespondentDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspondent_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_correspondent_defaults', to='contacts.contact')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_correspondent_defaults', to='wms.destination')),
            ],
            options={
                'ordering': ['destination__city', 'correspondent_org__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinationcorrespondentoverride',
            constraint=models.UniqueConstraint(fields=('destination', 'correspondent_org', 'shipper_org', 'recipient_org'), name='wms_destination_corr_override_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='destinationcorrespondentoverride',
            constraint=_check_constraint_compat(
                condition=models.Q(
                    ('shipper_org__isnull', False),
                    ('recipient_org__isnull', False),
                    _connector='OR',
                ),
                name='wms_destination_corr_override_requires_scope',
            ),
        ),
        migrations.AddConstraint(
            model_name='destinationcorrespondentdefault',
            constraint=models.UniqueConstraint(fields=('destination', 'correspondent_org'), name='wms_destination_corr_default_unique'),
        ),
    ]
