# Generated by Django 4.2.11 on 2026-03-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        ('wms', '0069_destinationcorrespondentoverride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shipment_status_updated', 'Mise a jour statut expedition'), ('shipment_delivered', 'Livraison expedition'), ('shipment_tracking_updated', 'Mise a jour tracking expedition'), ('order_document_requested', 'Demande de document commande')], max_length=60)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role_contact__role_assignment__organization__name', 'event_type', 'channel', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleEventPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper', 'Expéditeur'), ('recipient', 'Destinataire'), ('correspondent', 'Correspondant'), ('donor', 'Donateur'), ('transporter', 'Transporteur')], max_length=40)),
                ('event_type', models.CharField(choices=[('shipment_status_updated', 'Mise a jour statut expedition'), ('shipment_delivered', 'Livraison expedition'), ('shipment_tracking_updated', 'Mise a jour tracking expedition'), ('order_document_requested', 'Demande de document commande')], max_length=60)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_notifiable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'event_type', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='roleeventpolicy',
            constraint=models.UniqueConstraint(fields=('role', 'event_type'), name='wms_role_event_policy_unique_role_event'),
        ),
        migrations.AddField(
            model_name='contactsubscription',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_subscriptions', to='wms.destination'),
        ),
        migrations.AddField(
            model_name='contactsubscription',
            name='recipient_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_subscriptions_as_recipient', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactsubscription',
            name='role_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='wms.organizationrolecontact'),
        ),
        migrations.AddField(
            model_name='contactsubscription',
            name='shipper_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_subscriptions_as_shipper', to='contacts.contact'),
        ),
        migrations.AddConstraint(
            model_name='contactsubscription',
            constraint=models.UniqueConstraint(fields=('role_contact', 'event_type', 'channel', 'destination', 'shipper_org', 'recipient_org'), name='wms_contact_subscription_unique_filter_combo'),
        ),
    ]
