# Generated by Django 4.2.11 on 2026-03-04 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0070_contactsubscription_roleeventpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('ticket_reference', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expires_at', 'role_assignment__organization__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper', 'Expéditeur'), ('recipient', 'Destinataire'), ('correspondent', 'Correspondant'), ('donor', 'Donateur'), ('transporter', 'Transporteur')], max_length=40)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='organization_role_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_role_documents', to='wms.documentrequirementtemplate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_role_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_documents', to='wms.organizationroleassignment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_role_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role_assignment__organization__name', 'requirement_template__code', '-uploaded_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentrequirementtemplate',
            constraint=models.UniqueConstraint(fields=('role', 'code'), name='wms_doc_requirement_template_unique_role_code'),
        ),
        migrations.AddField(
            model_name='complianceoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_overrides_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceoverride',
            name='role_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_overrides', to='wms.organizationroleassignment'),
        ),
        migrations.AddConstraint(
            model_name='organizationroledocument',
            constraint=models.UniqueConstraint(fields=('role_assignment', 'requirement_template'), name='wms_role_document_unique_requirement'),
        ),
    ]
