# Generated by Django 4.2.11 on 2026-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0071_complianceoverride_documentrequirementtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='legacy_contact_write_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='org_roles_engine_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmsruntimesettings',
            name='org_roles_review_max_open_percent',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
