# Generated by Django 4.2.11 on 2026-03-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0072_wmsruntimesettings_legacy_contact_write_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper', 'Expéditeur'), ('recipient', 'Destinataire'), ('correspondent', 'Correspondant'), ('donor', 'Donateur'), ('transporter', 'Transporteur')], max_length=40)),
                ('reason_code', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Resolue')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migration_review_items_legacy', to='contacts.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migration_review_items_organization', to='contacts.contact')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_review_items_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='migrationreviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('legacy_contact', 'role', 'reason_code'), name='wms_migration_review_item_single_open_issue'),
        ),
    ]
