# Generated by Django 4.2.11 on 2026-03-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0073_migrationreviewitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wmsruntimesettings",
            name="legacy_contact_write_enabled",
        ),
    ]
