# Generated by Django 4.2.11 on 2026-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0074_remove_wmsruntimesettings_legacy_contact_write_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdocument',
            name='scan_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accountdocument',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Scan en cours'), ('clean', 'Sain'), ('infected', 'Infecte'), ('error', 'Erreur scan')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='accountdocument',
            name='scan_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Scan en cours'), ('clean', 'Sain'), ('infected', 'Infecte'), ('error', 'Erreur scan')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='scan_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Scan en cours'), ('clean', 'Sain'), ('infected', 'Infecte'), ('error', 'Erreur scan')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='scan_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
