# Generated by Django 4.2.11 on 2026-03-07 22:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_association_billing_profiles(apps, schema_editor):
    AssociationProfile = apps.get_model("wms", "AssociationProfile")
    AssociationBillingProfile = apps.get_model("wms", "AssociationBillingProfile")

    existing_ids = set(
        AssociationBillingProfile.objects.values_list("association_profile_id", flat=True)
    )
    missing_ids = [
        association_profile_id
        for association_profile_id in AssociationProfile.objects.values_list("id", flat=True)
        if association_profile_id not in existing_ids
    ]
    AssociationBillingProfile.objects.bulk_create(
        [
            AssociationBillingProfile(association_profile_id=association_profile_id)
            for association_profile_id in missing_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0075_accountdocument_scan_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_frequency', models.CharField(choices=[('per_shipment', 'Per shipment'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly')], default='per_shipment', max_length=30)),
                ('grouping_mode', models.CharField(choices=[('single_document', 'Single document'), ('per_shipment', 'Per shipment document')], default='single_document', max_length=30)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('billing_name_override', models.CharField(blank=True, max_length=200)),
                ('billing_address_override', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='wms.associationprofile')),
            ],
            options={
                'ordering': ['association_profile_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingComputationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_when_receipts_linked', models.BooleanField(blank=True, null=True)),
                ('base_unit_source', models.CharField(choices=[('shipped_units', 'Shipped units'), ('allocated_received_units', 'Allocated received units'), ('manual', 'Manual')], default='shipped_units', max_length=40)),
                ('base_step_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('base_step_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_unit_mode', models.CharField(choices=[('none', 'None'), ('shipped_minus_allocated_received', 'Shipped minus allocated received'), ('manual', 'Manual')], default='none', max_length=50)),
                ('extra_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allow_manual_override', models.BooleanField(default=False)),
                ('is_default_for_shipment_only', models.BooleanField(default=False)),
                ('is_default_for_receipt_linked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['label', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice'), ('credit_note', 'Credit note')], default='quote', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('quote_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('credit_note_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='wms.associationprofile')),
                ('computation_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='wms.billingcomputationprofile')),
                ('source_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='wms.billingdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('is_discount', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptShipmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_received_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_shipment_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_allocations', to='wms.receipt')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_allocations', to='wms.shipment')),
            ],
            options={
                'ordering': ['receipt_id', 'shipment_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('proof_attachment', models.FileField(blank=True, upload_to='billing/payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_payments_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wms.billingdocument')),
            ],
            options={
                'ordering': ['document_id', 'paid_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BillingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('resolution_comment', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='wms.billingdocument')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_issues_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_issues_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingDocumentShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_links', to='wms.billingdocument')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_document_links', to='wms.shipment')),
            ],
            options={
                'ordering': ['document_id', 'shipment_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingDocumentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_links', to='wms.billingdocument')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_document_links', to='wms.receipt')),
            ],
            options={
                'ordering': ['document_id', 'receipt_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_manual', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.billingdocument')),
                ('service_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_lines', to='wms.billingservicecatalogitem')),
            ],
            options={
                'ordering': ['document_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='BillingAssociationPriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('association_billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='wms.associationbillingprofile')),
                ('computation_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_overrides', to='wms.billingcomputationprofile')),
                ('service_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_overrides', to='wms.billingservicecatalogitem')),
            ],
            options={
                'ordering': ['association_billing_profile_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='associationbillingprofile',
            name='default_computation_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='association_defaults', to='wms.billingcomputationprofile'),
        ),
        migrations.RunPython(
            backfill_association_billing_profiles,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AssociationBillingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_frequency', models.CharField(choices=[('per_shipment', 'Per shipment'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly')], max_length=30)),
                ('requested_grouping_mode', models.CharField(choices=[('single_document', 'Single document'), ('per_shipment', 'Per shipment document')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('association_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_change_requests', to='wms.associationprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_change_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_change_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='receiptshipmentallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'shipment'), name='wms_receipt_shipment_allocation_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='billingdocumentshipment',
            constraint=models.UniqueConstraint(fields=('document', 'shipment'), name='wms_billing_document_shipment_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='billingdocumentreceipt',
            constraint=models.UniqueConstraint(fields=('document', 'receipt'), name='wms_billing_document_receipt_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='billingdocumentline',
            constraint=models.UniqueConstraint(fields=('document', 'line_number'), name='wms_billing_document_line_unique_number'),
        ),
    ]
