# Generated by Django 4.2.11 on 2026-03-08 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0080_billing_document_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentunitequivalencerule',
            name='units_per_item',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
