# Generated by Django 4.2.11 on 2026-03-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_linked_shippers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0081_alter_billingissue_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profiles', to='contacts.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['volunteer_id', 'user__last_name', 'user__first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='wms.volunteerprofile')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_expeditions_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_expeditions_per_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_wait_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='wms.volunteerprofile')),
            ],
            options={
                'ordering': ['volunteer__volunteer_id', 'volunteer_id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='wms.volunteerprofile')),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_volunteer_account_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='volunteerunavailability',
            constraint=models.UniqueConstraint(fields=('volunteer', 'date'), name='unique_volunteer_unavailability_per_day'),
        ),
    ]
