# Generated by Django 4.2.11 on 2026-03-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0082_volunteerprofile_volunteerunavailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('scope', models.CharField(blank=True, max_length=60)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=40)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('origin_iata', models.CharField(blank=True, max_length=10)),
                ('destination_iata', models.CharField(blank=True, max_length=10)),
                ('capacity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['departure_date', 'flight_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlightSourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('imported', 'Imported'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_parameter_sets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_current', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('flight_mode', models.CharField(choices=[('api', 'API'), ('excel', 'Excel'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('validation_failed', 'Validation failed'), ('ready', 'Ready'), ('solving', 'Solving'), ('solved', 'Solved'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('solver_payload', models.JSONField(blank=True, default=dict)),
                ('solver_result', models.JSONField(blank=True, default=dict)),
                ('log_excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_runs_created', to=settings.AUTH_USER_MODEL)),
                ('flight_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_runs', to='wms.flightsourcebatch')),
                ('parameter_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_runs', to='wms.planningparameterset')),
            ],
            options={
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningVolunteerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_label', models.CharField(blank=True, max_length=160)),
                ('max_colis_vol', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('availability_summary', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_snapshots', to='wms.planningrun')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_snapshots', to='wms.volunteerprofile')),
            ],
            options={
                'ordering': ['run_id', 'volunteer_label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='wms.planningversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_versions_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wms.planningrun')),
            ],
            options={
                'ordering': ['run_id', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningShipmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_reference', models.CharField(blank=True, max_length=80)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('destination_iata', models.CharField(blank=True, max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('carton_count', models.PositiveIntegerField(default=0)),
                ('equivalent_units', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_snapshots', to='wms.planningrun')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_snapshots', to='wms.shipment')),
            ],
            options={
                'ordering': ['run_id', 'priority', 'shipment_reference', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=20)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='wms.planningrun')),
            ],
            options={
                'ordering': ['run_id', 'severity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningFlightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=40)),
                ('departure_date', models.DateField()),
                ('destination_iata', models.CharField(blank=True, max_length=10)),
                ('capacity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_snapshots', to='wms.flight')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_snapshots', to='wms.planningrun')),
            ],
            options={
                'ordering': ['run_id', 'departure_date', 'flight_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningDestinationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('weekly_frequency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_cartons_per_flight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_destination_rules', to='wms.destination')),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rules', to='wms.planningparameterset')),
            ],
            options={
                'ordering': ['parameter_set_id', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_carton_count', models.PositiveIntegerField(default=0)),
                ('assigned_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(default='proposed', max_length=30)),
                ('source', models.CharField(choices=[('solver', 'Solver'), ('manual', 'Manual'), ('copied', 'Copied')], default='solver', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='wms.planningflightsnapshot')),
                ('shipment_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='wms.planningshipmentsnapshot')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='wms.planningversion')),
                ('volunteer_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='wms.planningvolunteersnapshot')),
            ],
            options={
                'ordering': ['version_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='wms.planningversion')),
            ],
            options={
                'ordering': ['version_id', 'artifact_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='wms.flightsourcebatch'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_flights', to='wms.destination'),
        ),
        migrations.CreateModel(
            name='CommunicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('recipient_label', models.CharField(blank=True, max_length=255)),
                ('recipient_contact', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('edited', 'Edited'), ('exported', 'Exported'), ('sent_manually', 'Sent manually')], default='generated', max_length=30)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_communication_drafts_edited', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='wms.communicationtemplate')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_drafts', to='wms.planningversion')),
            ],
            options={
                'ordering': ['version_id', 'channel', 'recipient_label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planningversion',
            constraint=models.UniqueConstraint(fields=('run', 'number'), name='unique_planning_version_number_per_run'),
        ),
    ]
