# Generated by Django 4.2.11 on 2026-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0083_communicationtemplate_flight_flightsourcebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerconstraint',
            name='max_colis_vol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
