# Generated by Django 4.2.11 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0084_volunteerconstraint_max_colis_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='route_pos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='routing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
