# Generated by Django 5.2.12 on 2026-03-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0090_delete_migrationreviewitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmsruntimesettings',
            name='org_roles_engine_enabled',
        ),
    ]
