# Generated by Django 5.2.12 on 2026-03-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0008_remove_contact_tags_remove_contact_destination_and_more"),
        ("wms", "0093_remove_legacy_ui_mode_and_design_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentRecipientOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validated", "Valide"),
                            ("rejected", "Refuse"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_correspondent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_recipient_organizations",
                        to="wms.destination",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_recipient_organizations",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["destination__city", "organization__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentRecipientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_recipient_contacts",
                        to="contacts.contact",
                    ),
                ),
                (
                    "recipient_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_contacts",
                        to="wms.shipmentrecipientorganization",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "recipient_organization__organization__name",
                    "contact__last_name",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="ShipmentShipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validated", "Valide"),
                            ("rejected", "Refuse"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("can_send_to_all", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_shipper_defaults",
                        to="contacts.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_shippers",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentShipperRecipientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipient_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipper_links",
                        to="wms.shipmentrecipientorganization",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_links",
                        to="wms.shipmentshipper",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "shipper__organization__name",
                    "recipient_organization__organization__name",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="ShipmentAuthorizedRecipientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipient_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_links",
                        to="wms.shipmentrecipientcontact",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_recipient_contacts",
                        to="wms.shipmentshipperrecipientlink",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "link__shipper__organization__name",
                    "-is_default",
                    "recipient_contact__contact__last_name",
                    "id",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="shipmentrecipientorganization",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="wms_shipment_recipient_org_unique_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentrecipientorganization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_correspondent", True)),
                fields=("destination",),
                name="wms_shipment_recipient_org_single_active_correspondent",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentrecipientcontact",
            constraint=models.UniqueConstraint(
                fields=("recipient_organization", "contact"),
                name="wms_shipment_recipient_contact_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentshipper",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="wms_shipment_shipper_unique_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentshipperrecipientlink",
            constraint=models.UniqueConstraint(
                fields=("shipper", "recipient_organization"),
                name="wms_shipment_shipper_recipient_link_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentauthorizedrecipientcontact",
            constraint=models.UniqueConstraint(
                fields=("link", "recipient_contact"),
                name="wms_shipment_authorized_recipient_contact_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentauthorizedrecipientcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("link",),
                name="wms_shipment_authorized_recipient_contact_single_default",
            ),
        ),
    ]
