# Generated by Django 5.2.12 on 2026-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0094_shipment_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='party_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
