# Generated by Django 5.2.12 on 2026-03-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0095_shipment_party_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wmsruntimesettings",
            name="org_roles_review_max_open_percent",
        ),
        migrations.DeleteModel(
            name="ContactSubscription",
        ),
        migrations.DeleteModel(
            name="ComplianceOverride",
        ),
        migrations.DeleteModel(
            name="OrganizationRoleDocument",
        ),
        migrations.DeleteModel(
            name="OrganizationRoleContact",
        ),
        migrations.DeleteModel(
            name="RecipientBinding",
        ),
        migrations.DeleteModel(
            name="ShipperScope",
        ),
        migrations.DeleteModel(
            name="RoleEventPolicy",
        ),
        migrations.DeleteModel(
            name="DocumentRequirementTemplate",
        ),
        migrations.DeleteModel(
            name="OrganizationContact",
        ),
        migrations.DeleteModel(
            name="OrganizationRoleAssignment",
        ),
    ]
