# Generated by Django 5.2.12 on 2026-03-30 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_beneficiary_count_contact_legal_form'),
        ('wms', '0099_shipment_dossier_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associationrecipient',
            name='beneficiary_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associationrecipient',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('association', 'Association'), ('private_sector', 'Secteur privé'), ('public_sector', 'Publique'), ('other', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='RecipientStructureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registration_proof', 'Preuve enregistrement'), ('statutes', 'Statuts')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file', models.FileField(upload_to='recipient_structure_documents/')),
                ('scan_status', models.CharField(choices=[('pending', 'Scan en cours'), ('clean', 'Sain'), ('infected', 'Infecte'), ('error', 'Erreur scan')], default='clean', max_length=20)),
                ('scan_message', models.CharField(blank=True, max_length=255)),
                ('scan_updated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_structure_documents', to='contacts.contact')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_structure_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'doc_type'), name='wms_recipient_structure_doc_unique')],
            },
        ),
    ]
