# Generated by Django 5.2.12 on 2026-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0100_associationrecipient_beneficiary_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientstructuredocument',
            name='doc_type',
            field=models.CharField(choices=[('registration_proof', "Preuve d'enregistrement"), ('statutes', 'Statut')], max_length=40),
        ),
    ]
