# Generated by Django 5.2.12 on 2026-04-01 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wms", "0102_shipmentworkflowprojection"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsPilotageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("scope_type", models.CharField(max_length=40)),
                ("scope_key", models.CharField(max_length=120)),
                ("metric_key", models.CharField(max_length=80)),
                ("metric_value", models.FloatField(default=0.0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-snapshot_date", "scope_type", "scope_key", "metric_key", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="opspilotagesnapshot",
            index=models.Index(
                fields=["snapshot_date", "scope_type"],
                name="wms_ops_snap_date_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opspilotagesnapshot",
            index=models.Index(
                fields=["scope_type", "metric_key"],
                name="wms_ops_snap_scope_metric_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="opspilotagesnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "scope_type", "scope_key", "metric_key"),
                name="wms_ops_snapshot_unique_metric",
            ),
        ),
    ]
