# Generated by Django 5.2.12 on 2026-04-01 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wms", "0103_opspilotagesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmsruntimesettings",
            name="pilotage_dispute_unassigned_hours",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="wmsruntimesettings",
            name="pilotage_queue_backlog_threshold",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="wmsruntimesettings",
            name="pilotage_workflow_blockage_unclaimed_hours",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name="OpsEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escalation_key", models.CharField(max_length=160, unique=True)),
                ("category", models.CharField(max_length=40)),
                ("scope_type", models.CharField(max_length=40)),
                ("scope_key", models.CharField(max_length=120)),
                ("severity", models.CharField(max_length=20)),
                ("owner", models.CharField(blank=True, default="", max_length=20)),
                ("status", models.CharField(default="open", max_length=20)),
                ("first_detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["status", "-last_detected_at", "category", "escalation_key"],
            },
        ),
        migrations.AddIndex(
            model_name="opsescalation",
            index=models.Index(
                fields=["status", "category"],
                name="wms_ops_esc_status_cat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opsescalation",
            index=models.Index(
                fields=["scope_type", "scope_key"],
                name="wms_ops_esc_scope_idx",
            ),
        ),
    ]
