# Generated by Django 5.2.12 on 2026-04-01 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wms", "0104_opsescalation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningCommunicationArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output_type", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=20)),
                ("backend", models.CharField(blank=True, default="", max_length=40)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("error_message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "planning_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_artifacts",
                        to="wms.planningversion",
                    ),
                ),
            ],
            options={
                "ordering": ["planning_version_id", "output_type", "-generated_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="planningcommunicationartifact",
            index=models.Index(
                fields=["planning_version", "output_type", "-generated_at"],
                name="wms_plan_comm_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningcommunicationartifact",
            index=models.Index(
                fields=["output_type", "status"],
                name="wms_plan_comm_status_idx",
            ),
        ),
    ]
