# Generated by Django 5.2.12 on 2026-04-02 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0107_merge_20260401_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(max_length=80)),
                ('trigger_source', models.CharField(default='direct', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', 'job_key', '-id'],
                'indexes': [models.Index(fields=['job_key', '-started_at'], name='wms_job_run_key_start_idx'), models.Index(fields=['status', '-started_at'], name='wms_job_run_status_idx')],
            },
        ),
    ]
