# Generated by Django 5.2.12 on 2026-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_beneficiary_count_contact_legal_form'),
        ('wms', '0108_operationaljobrun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipmentrecipientorganization',
            name='wms_shipment_recipient_org_unique_organization',
        ),
        migrations.AddConstraint(
            model_name='shipmentrecipientorganization',
            constraint=models.UniqueConstraint(fields=('organization', 'destination'), name='wms_shipment_recipient_org_unique_org_destination'),
        ),
    ]
