# Generated by Django 5.2.12 on 2026-04-05 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0109_remove_shipmentrecipientorganization_wms_shipment_recipient_org_unique_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationCartonProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('deposit', 'Deposit'), ('asf_stock', 'ASF stock'), ('mixed', 'Mixed')], max_length=24)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected'), ('needs_recalc', 'Needs recalc'), ('converted', 'Converted')], default='proposed', max_length=24)),
                ('quantity', models.PositiveIntegerField()),
                ('equivalent_units_total', models.PositiveIntegerField(default=0)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_carton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_proposals', to='wms.carton')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation_carton_proposals', to='wms.product')),
            ],
            options={
                'ordering': ['shipment_proposal_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_parameter_sets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_current', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_equivalent_units', models.PositiveIntegerField()),
                ('target_shipment_count', models.PositiveIntegerField()),
                ('target_shipment_size_units', models.PositiveIntegerField(default=10)),
                ('min_shipment_size_units', models.PositiveIntegerField(default=1)),
                ('max_shipment_size_units', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_window_start', models.DateField()),
                ('flight_window_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('frozen', 'Frozen'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('parameter_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_runs_created', to=settings.AUTH_USER_MODEL)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='wms.preparationparameterset')),
            ],
            options={
                'ordering': ['-flight_window_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationShipmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('deposit', 'Deposit'), ('asf_stock', 'ASF stock'), ('mixed', 'Mixed')], max_length=24)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected'), ('needs_recalc', 'Needs recalc'), ('converted', 'Converted')], default='proposed', max_length=24)),
                ('equivalent_units_total', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_proposals', to='wms.shipment')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_shipment_proposals', to='wms.destination')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_shipment_proposals', to='wms.shipmentrecipientorganization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_proposals', to='wms.preparationrun')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_shipment_proposals', to='wms.shipmentshipper')),
            ],
            options={
                'ordering': ['run_id', 'shipper_id', 'recipient_organization_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed')], default='active', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carton_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='wms.preparationcartonproposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_reservations', to='wms.productlot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='wms.preparationrun')),
                ('shipment_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='wms.preparationshipmentproposal')),
            ],
            options={
                'ordering': ['run_id', 'shipment_proposal_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject_keep_draft', 'Reject and keep draft'), ('reject_delete', 'Reject and delete'), ('reclaim_for_urgency', 'Reclaim for urgency')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('carton_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='wms.preparationcartonproposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_decision_logs_created', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='wms.preparationreservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='wms.preparationrun')),
                ('shipment_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='wms.preparationshipmentproposal')),
            ],
            options={
                'ordering': ['run_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='preparationcartonproposal',
            name='shipment_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_proposals', to='wms.preparationshipmentproposal'),
        ),
        migrations.CreateModel(
            name='PreparationShipperRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('deposit_only', 'Deposit only'), ('asf_complement_allowed', 'ASF complement allowed'), ('asf_auto_allowed', 'ASF auto allowed')], default='deposit_only', max_length=32)),
                ('score_coefficient', models.DecimalField(decimal_places=2, default='1.00', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_rules', to='wms.preparationparameterset')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_rules', to='wms.shipmentshipper')),
            ],
            options={
                'ordering': ['parameter_set_id', 'shipper_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPreparationNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_unit', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='week', max_length=16)),
                ('target_equivalent_units', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_preparation_needs_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_preparation_needs', to='wms.destination')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_preparation_needs', to='wms.shipmentrecipientorganization')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_preparation_needs', to='wms.shipmentshipper')),
            ],
            options={
                'ordering': ['shipper_id', 'recipient_organization_id', 'destination_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationRunNeedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_unit', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], max_length=16)),
                ('target_equivalent_units', models.PositiveIntegerField()),
                ('snapshot_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_need_snapshots', to='wms.destination')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_need_snapshots', to='wms.shipmentrecipientorganization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_snapshots', to='wms.preparationrun')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_need_snapshots', to='wms.shipmentshipper')),
                ('recurring_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_snapshots', to='wms.recurringpreparationneed')),
            ],
            options={
                'ordering': ['run_id', 'shipper_id', 'recipient_organization_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationDestinationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_equivalent_units_per_flight', models.PositiveIntegerField(blank=True, null=True)),
                ('max_usable_flights_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('max_equivalent_units_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('max_shipments_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_weekdays', models.JSONField(blank=True, default=list)),
                ('fairness_weight', models.DecimalField(decimal_places=2, default='1.00', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_destination_rules', to='wms.destination')),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rules', to='wms.preparationparameterset')),
            ],
            options={
                'ordering': ['parameter_set_id', 'destination__city', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parameter_set', 'destination'), name='wms_prep_dest_rule_unique_parameter_destination')],
            },
        ),
        migrations.AddConstraint(
            model_name='preparationshipmentproposal',
            constraint=models.UniqueConstraint(fields=('run', 'shipper', 'recipient_organization', 'destination', 'sequence'), name='wms_prep_ship_prop_unique_run_scope_sequence'),
        ),
        migrations.AddConstraint(
            model_name='preparationshipperrule',
            constraint=models.UniqueConstraint(fields=('parameter_set', 'shipper'), name='wms_prep_shipper_rule_unique_parameter_shipper'),
        ),
        migrations.AddConstraint(
            model_name='recurringpreparationneed',
            constraint=models.UniqueConstraint(fields=('shipper', 'recipient_organization', 'destination'), name='wms_recurring_prep_need_unique_scope'),
        ),
    ]
