# Generated by Django 5.2.12 on 2026-04-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0109_remove_shipmentrecipientorganization_wms_shipment_recipient_org_unique_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPreferenceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_status_snapshot', models.CharField(choices=[('requested', 'Demande'), ('allowed', 'Autorise'), ('refused', 'Refuse')], max_length=20)),
                ('action', models.CharField(choices=[('override_refusal', 'Override refus')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_overrides', to='wms.carton')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_preference_overrides', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_preference_overrides', to='wms.product')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preference_overrides', to='wms.shipmentrecipientorganization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preference_overrides', to='wms.shipment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecipientProductPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Demande'), ('allowed', 'Autorise'), ('refused', 'Refuse')], max_length=20)),
                ('quantity_target', models.PositiveIntegerField(blank=True, null=True)),
                ('period_unit', models.CharField(blank=True, choices=[('week', 'Semaine'), ('month', 'Mois')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('portal', 'Portail'), ('scan_admin', 'Scan admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipient_product_preferences', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_preferences', to='wms.product')),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_preferences', to='wms.shipmentrecipientorganization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recipient_product_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recipient_organization__destination__city', 'recipient_organization__organization__name', 'product__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recipient_organization', 'product'), name='wms_recipient_product_preference_unique_pair')],
            },
        ),
    ]
