# Generated by Django 5.2.12 on 2026-04-05 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0110_preparationcartonproposal_preparationparameterset_and_more"),
        ("wms", "0110_shipmentpreferenceoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientproductpreference",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipient_preferences",
                to="wms.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="recipientproductpreference",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipient_preferences",
                to="wms.product",
            ),
        ),
        migrations.AlterField(
            model_name="recipientproductpreference",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("portal", "Portail"),
                    ("scan_admin", "Scan admin"),
                    ("system", "Systeme"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="recipientproductpreference",
            name="wms_recipient_product_preference_unique_pair",
        ),
        migrations.AddConstraint(
            model_name="recipientproductpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("recipient_organization", "product"),
                name="wms_recipient_product_pref_unique_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipientproductpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category__isnull", False)),
                fields=("recipient_organization", "category"),
                name="wms_recipient_product_pref_unique_category",
            ),
        ),
    ]
