# Generated by Django 5.2.12 on 2026-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0111_shipmentpreferenceoverride_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipientproductpreference",
            options={
                "ordering": [
                    "recipient_organization__destination__city",
                    "recipient_organization__organization__name",
                    "id",
                ],
            },
        ),
        migrations.AlterField(
            model_name="shipmentpreferenceoverride",
            name="action",
            field=models.CharField(
                choices=[("override_refusal", "Override refusal")],
                default="override_refusal",
                max_length=30,
            ),
        ),
    ]
