# Generated by Django 5.2.12 on 2026-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0112_alter_recipientproductpreference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='conformity_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('conform', 'Conform'), ('non_conform', 'Non-conform')], default='unknown', max_length=20),
        ),
    ]
