# Generated by Django 5.2.12 on 2026-04-08 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0113_receipt_conformity_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper_admin', 'Administrateur expediteur'), ('recipient_admin', 'Administrateur destinataire')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_grants', to='wms.shipmentrecipientorganization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access_grants_reviewed', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_grants', to='wms.shipmentshipper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'role', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shipper__isnull', False), ('recipient_organization__isnull', True)), models.Q(('shipper__isnull', True), ('recipient_organization__isnull', False)), _connector='OR'), name='wms_portal_access_grant_exactly_one_scope'), models.UniqueConstraint(condition=models.Q(('shipper__isnull', False)), fields=('user', 'role', 'shipper'), name='wms_portal_access_grant_unique_shipper_scope'), models.UniqueConstraint(condition=models.Q(('recipient_organization__isnull', False)), fields=('user', 'role', 'recipient_organization'), name='wms_portal_access_grant_unique_recipient_scope')],
            },
        ),
    ]
