# Generated by Django 5.2.12 on 2026-04-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0114_portalaccessgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccountrequest',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_account_requests', to='wms.destination'),
        ),
        migrations.AlterField(
            model_name='publicaccountrequest',
            name='account_type',
            field=models.CharField(choices=[('association', 'Association'), ('shipper', 'Expediteur'), ('recipient', 'Destinataire'), ('user', 'Utilisateur WMS')], db_index=True, default='association', max_length=20),
        ),
    ]
