# Generated by Django 5.2.12 on 2026-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0116_fix_pack_b_packing_list_carton_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
