# Generated by Django 5.2.12 on 2026-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0117_product_is_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccountrequest',
            name='requested_account_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publicaccountrequest',
            name='review_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
