# Generated by Django 5.2.12 on 2026-04-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_is_humanitarian_attestation_exempt'),
        ('wms', '0118_publicaccountrequest_requested_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='source_kind',
            field=models.CharField(choices=[('warehouse_prepared', 'Préparation ASF'), ('shipper_received', 'Réception expéditeur')], default='warehouse_prepared', max_length=30),
        ),
        migrations.AddField(
            model_name='carton',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_cartons', to='wms.receipt'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='doc_type',
            field=models.CharField(choices=[('donation_attestation', 'Attestation donation'), ('humanitarian_attestation', 'Attestation aide humanitaire'), ('packing_list_global', 'Liste de colisage globale'), ('packing_list_by_carton', 'Liste de colisage par colis'), ('invoice', 'Facture'), ('other', 'Autre')], max_length=40),
        ),
        migrations.CreateModel(
            name='AssociationPickupAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('pickup_company_name', models.CharField(blank=True, max_length=200)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=200)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=40)),
                ('pickup_contact_phone_2', models.CharField(blank=True, max_length=40)),
                ('pickup_address_line1', models.CharField(blank=True, max_length=200)),
                ('pickup_address_line2', models.CharField(blank=True, max_length=200)),
                ('pickup_postal_code', models.CharField(blank=True, max_length=20)),
                ('pickup_city', models.CharField(blank=True, max_length=120)),
                ('pickup_country', models.CharField(default='France', max_length=80)),
                ('pickup_opening_slot_1_start', models.TimeField(blank=True, null=True)),
                ('pickup_opening_slot_1_end', models.TimeField(blank=True, null=True)),
                ('pickup_has_midday_break', models.BooleanField(default=False)),
                ('pickup_opening_slot_2_start', models.TimeField(blank=True, null=True)),
                ('pickup_opening_slot_2_end', models.TimeField(blank=True, null=True)),
                ('pickup_has_no_access_constraints', models.BooleanField(default=False)),
                ('pickup_access_constraints_details', models.TextField(blank=True)),
                ('tail_lift_required', models.BooleanField(default=True)),
                ('pallet_truck_required', models.BooleanField(default=True)),
                ('pickup_information_confirmed', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_addresses', to='contacts.contact')),
            ],
            options={
                'ordering': ['association_contact__name', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderInboundDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_mode', models.CharField(choices=[('dropoff_warehouse', "Dépôt à l'entrepôt"), ('pickup_requested', 'Enlèvement demandé')], max_length=30)),
                ('declared_carton_count', models.PositiveIntegerField(default=0)),
                ('declared_out_of_format_count', models.PositiveIntegerField(default=0)),
                ('pickup_company_name', models.CharField(blank=True, max_length=200)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=200)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=40)),
                ('pickup_contact_phone_2', models.CharField(blank=True, max_length=40)),
                ('pickup_address_line1', models.CharField(blank=True, max_length=200)),
                ('pickup_address_line2', models.CharField(blank=True, max_length=200)),
                ('pickup_postal_code', models.CharField(blank=True, max_length=20)),
                ('pickup_city', models.CharField(blank=True, max_length=120)),
                ('pickup_country', models.CharField(default='France', max_length=80)),
                ('pickup_available_from_date', models.DateField(blank=True, null=True)),
                ('pickup_requested_for_date', models.DateField(blank=True, null=True)),
                ('pickup_opening_slot_1_start', models.TimeField(blank=True, null=True)),
                ('pickup_opening_slot_1_end', models.TimeField(blank=True, null=True)),
                ('pickup_has_midday_break', models.BooleanField(default=False)),
                ('pickup_opening_slot_2_start', models.TimeField(blank=True, null=True)),
                ('pickup_opening_slot_2_end', models.TimeField(blank=True, null=True)),
                ('pickup_has_no_access_constraints', models.BooleanField(default=False)),
                ('pickup_access_constraints_details', models.TextField(blank=True)),
                ('tail_lift_required', models.BooleanField(default=True)),
                ('pallet_truck_required', models.BooleanField(default=True)),
                ('pickup_information_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_delivery', to='wms.order')),
                ('pickup_address_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_inbound_deliveries', to='wms.associationpickupaddress')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_inbound_delivery', to='wms.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_links', to='wms.order')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='wms.shipment')),
            ],
            options={
                'ordering': ['order_id', 'shipment_id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'shipment'), name='wms_order_shipment_link_unique')],
            },
        ),
    ]
