# Generated by Django 5.2.12 on 2026-04-20 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_is_humanitarian_attestation_exempt'),
        ('wms', '0119_carton_source_kind_carton_source_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='actor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='actor_identifier',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='actor_identity_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='actor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='auth_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='escale_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='proof_carton_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='shipment_tracking_proofs/'),
        ),
        migrations.AddField(
            model_name='shipmenttrackingevent',
            name='proof_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentTrackingAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('volunteer', 'Bénévole'), ('shipper', 'Expéditeur'), ('recipient', 'Destinataire'), ('correspondent', 'Correspondant')], max_length=40)),
                ('identity_status', models.CharField(choices=[('verified', 'Vérifié'), ('pending', 'En attente')], default='verified', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tracking_access_grants', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_tracking_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tracking_access_grants', to='wms.destination')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_tracking_access_grants_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tracking_access_grants', to=settings.AUTH_USER_MODEL)),
                ('volunteer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_tracking_access_grants', to='wms.volunteerprofile')),
            ],
            options={
                'ordering': ['user_id', 'role', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('volunteer_profile__isnull', True)), models.Q(('contact__isnull', True), ('volunteer_profile__isnull', False)), _connector='OR'), name='wms_tracking_access_grant_exactly_one_identity'), models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('user', 'role', 'contact'), name='wms_tracking_access_grant_unique_contact_scope'), models.UniqueConstraint(condition=models.Q(('volunteer_profile__isnull', False)), fields=('user', 'role', 'volunteer_profile'), name='wms_tracking_access_grant_unique_volunteer_scope')],
            },
        ),
    ]
