# Generated by Django 5.2.12 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0121_merge_20260421_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsruntimesettings',
            name='enable_shipment_track_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
