# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0122_alter_enable_shipment_track_legacy_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmenttrackingaccessgrant",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
