# Generated by Django 5.2.13 on 2026-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0123_shipmenttrackingaccessgrant_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingservicecatalogitem',
            name='use_for_default_pickup_charge',
            field=models.BooleanField(default=False),
        ),
    ]
