# Generated by Django 5.2.13 on 2026-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0124_billing_service_default_pickup_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='planned_carton_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
