# Generated by Django 5.2.13 on 2026-05-05 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0125_shipment_planned_carton_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalOnboardingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('shipper_admin', 'Administrateur expediteur'), ('recipient_admin', 'Administrateur destinataire')], max_length=40)),
                ('show_on_next_login', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_onboarding_preferences', to='wms.associationprofile')),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_onboarding_preferences', to='wms.shipmentrecipientorganization')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_onboarding_preferences', to='wms.shipmentshipper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_onboarding_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'role', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shipper__isnull', False), ('recipient_organization__isnull', True), ('association_profile__isnull', True)), models.Q(('shipper__isnull', True), ('recipient_organization__isnull', False), ('association_profile__isnull', True)), models.Q(('shipper__isnull', True), ('recipient_organization__isnull', True), ('association_profile__isnull', False)), _connector='OR'), name='wms_portal_onboarding_exactly_one_scope'), models.UniqueConstraint(condition=models.Q(('shipper__isnull', False)), fields=('user', 'role', 'shipper'), name='wms_portal_onboarding_unique_shipper'), models.UniqueConstraint(condition=models.Q(('recipient_organization__isnull', False)), fields=('user', 'role', 'recipient_organization'), name='wms_portal_onboarding_unique_recipient'), models.UniqueConstraint(condition=models.Q(('association_profile__isnull', False)), fields=('user', 'role', 'association_profile'), name='wms_portal_onboarding_unique_legacy_profile')],
            },
        ),
    ]
