# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0126_portalonboardingpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationpickupaddress",
            name="pickup_open_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="orderinbounddelivery",
            name="pickup_open_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
