# Generated by Django 5.2.13 on 2026-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0127_pickup_open_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationbillingchangerequest',
            name='requested_frequency',
            field=models.CharField(choices=[('per_shipment', 'Par expédition'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('half_yearly', 'Semestrielle'), ('yearly', 'Annuelle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='associationbillingchangerequest',
            name='requested_grouping_mode',
            field=models.CharField(choices=[('single_document', 'Document unique'), ('per_shipment', 'Un document par expédition')], max_length=30),
        ),
        migrations.AlterField(
            model_name='associationbillingchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='associationbillingprofile',
            name='billing_frequency',
            field=models.CharField(choices=[('per_shipment', 'Par expédition'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('half_yearly', 'Semestrielle'), ('yearly', 'Annuelle')], default='per_shipment', max_length=30),
        ),
        migrations.AlterField(
            model_name='associationbillingprofile',
            name='grouping_mode',
            field=models.CharField(choices=[('single_document', 'Document unique'), ('per_shipment', 'Un document par expédition')], default='single_document', max_length=30),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='correction_state',
            field=models.CharField(choices=[('none', 'Aucune'), ('in_review', 'En revue'), ('resolved', 'Résolue')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='kind',
            field=models.CharField(choices=[('quote', 'Devis'), ('invoice', 'Facture'), ('credit_note', 'Avoir')], default='quote', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émis'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('cancelled_or_corrected', 'Annulé / corrigé')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='billingissue',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('in_review', 'En cours'), ('resolved', 'Résolue')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('cash', 'Espèces'), ('card', 'Carte'), ('other', 'Autre')], default='bank_transfer', max_length=30),
        ),
    ]
