# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0128_alter_associationbillingchangerequest_requested_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinbounddelivery",
            name="declared_pallet_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderinbounddelivery",
            name="parcel_guidelines_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
