# Generated by Django 5.2.14 on 2026-05-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_is_humanitarian_attestation_exempt'),
        ('wms', '0131_accountdocument_document_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalOrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_order_drafts', to='contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_order_drafts', to=settings.AUTH_USER_MODEL)),
                ('submitted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_source_drafts', to='wms.order')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('created_by', 'association_contact'), name='wms_portal_order_draft_one_active')],
            },
        ),
    ]
