# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0132_portal_order_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StopoverFeasibilityRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester_type",
                    models.CharField(
                        choices=[
                            ("shipper", "Expediteur"),
                            ("recipient", "Destinataire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_stopovers", models.TextField()),
                ("structure_name", models.CharField(max_length=200)),
                (
                    "legal_form",
                    models.CharField(
                        choices=[
                            ("association", "Association"),
                            ("private_sector", "Secteur privé"),
                            ("public_sector", "Publique"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("beneficiary_count", models.PositiveIntegerField()),
                (
                    "contact_title",
                    models.CharField(
                        choices=[
                            ("mr", "M."),
                            ("mrs", "Mme"),
                            ("ms", "Mlle"),
                            ("dr", "Dr"),
                            ("pr", "Pr"),
                            ("pere", "Père"),
                            ("soeur", "Sœur"),
                            ("frere", "Frère"),
                            ("abbe", "Abbé"),
                            ("imam", "Imam"),
                            ("rabbin", "Rabbin"),
                            ("pasteur", "Pasteur"),
                            ("eveque", "Évêque"),
                            ("mons", "Monseigneur"),
                            ("president", "Président"),
                            ("ministre", "Ministre"),
                            ("ambassad", "Ambassadeur"),
                            ("maire", "Maire"),
                            ("prefet", "Préfet"),
                            ("gouvern", "Gouverneur"),
                            ("depute", "Député"),
                            ("senateur", "Sénateur"),
                            ("gen", "Général"),
                            ("colonel", "Colonel"),
                            ("cmdt", "Commandant"),
                            ("cpt", "Capitaine"),
                            ("lt", "Lieutenant"),
                            ("adj", "Adjudant"),
                            ("sgt", "Sergent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contact_last_name", models.CharField(max_length=120)),
                ("contact_first_name", models.CharField(max_length=120)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=40)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=80)),
                ("message", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("reviewed", "Etudiee"),
                            ("closed", "Cloturee"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stopover_feasibility_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
