# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0133_stopover_feasibility_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicaccountrequest",
            name="contact_payloads",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
