# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0134_publicaccountrequest_contact_payloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationportalcontact",
            name="address_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="address_line2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="country",
            field=models.CharField(default="France", max_length=80),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="emails",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="phones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="associationportalcontact",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
