# Generated by Django 5.2.14 on 2026-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0135_associationportalcontact_operational_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccountrequest',
            name='shipper_stopover_indications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
