from __future__ import annotations

DEFAULT_COUNTRY = "France"

# Local copy of the world-country display names so portal/admin choices remain stable
# without introducing a runtime dependency for ISO country metadata.
WORLD_COUNTRY_NAMES = (
    "Afghanistan",
    "Afrique du Sud",
    "Albanie",
    "Algérie",
    "Allemagne",
    "Andorre",
    "Angola",
    "Anguilla",
    "Antarctique",
    "Antigua-et-Barbuda",
    "Arabie saoudite",
    "Argentine",
    "Arménie",
    "Aruba",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahreïn",
    "Bangladesh",
    "Barbade",
    "Belgique",
    "Belize",
    "Bénin",
    "Bermudes",
    "Bhoutan",
    "Biélorussie",
    "Birmanie",
    "Bolivie",
    "Bonaire, Saint-Eustache et Saba",
    "Bosnie-Herzégovine",
    "Botswana",
    "Brésil",
    "Brunei Darussalam",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Cap-Vert",
    "Chili",
    "Chine",
    "Chypre",
    "Colombie",
    "Comores",
    "Congo",
    "Corée du Nord",
    "Corée du Sud",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatie",
    "Cuba",
    "Curaçao",
    "Danemark",
    "Djibouti",
    "Dominique",
    "Égypte",
    "Émirats arabes unis",
    "Équateur",
    "Érythrée",
    "Espagne",
    "Eswatini",
    "Estonie",
    "États fédérés de Micronésie",
    "États-Unis",
    "Éthiopie",
    "Fidji",
    "Finlande",
    "France",
    "Gabon",
    "Gambie",
    "Géorgie",
    "Géorgie du Sud-et-les Îles Sandwich du Sud",
    "Ghana",
    "Gibraltar",
    "Grèce",
    "Grenade",
    "Groenland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernesey",
    "Guinée",
    "Guinée-Bissau",
    "Guinée équatoriale",
    "Guyana",
    "Guyane française",
    "Haïti",
    "Honduras",
    "Hong Kong",
    "Hongrie",
    "Île Bouvet",
    "Île Christmas",
    "Île de Man",
    "Île Norfolk",
    "Îles Åland",
    "Îles Caïmans",
    "Îles Cocos",
    "Îles Cook",
    "Îles Féroé",
    "Îles Heard-et-MacDonald",
    "Îles Malouines",
    "Îles Mariannes du Nord",
    "Îles Marshall",
    "Îles mineures éloignées des États-Unis",
    "Îles Pitcairn",
    "Îles Salomon",
    "Îles Turques-et-Caïques",
    "Îles Vierges britanniques",
    "Îles Vierges des États-Unis",
    "Inde",
    "Indonésie",
    "Irak",
    "Iran",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "Jamaïque",
    "Japon",
    "Jersey",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kirghizistan",
    "Kiribati",
    "Koweït",
    "Laos",
    "Lesotho",
    "Lettonie",
    "Liban",
    "Liberia",
    "Libye",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macao",
    "Macédoine du Nord",
    "Madagascar",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Mali",
    "Malte",
    "Maroc",
    "Martinique",
    "Maurice",
    "Mauritanie",
    "Mayotte",
    "Mexique",
    "Moldavie",
    "Monaco",
    "Mongolie",
    "Monténégro",
    "Montserrat",
    "Mozambique",
    "Namibie",
    "Nauru",
    "Népal",
    "Nicaragua",
    "Niger",
    "Nigéria",
    "Niue",
    "Norvège",
    "Nouvelle-Calédonie",
    "Nouvelle-Zélande",
    "Oman",
    "Ouganda",
    "Ouzbékistan",
    "Pakistan",
    "Palaos",
    "Palestine",
    "Panama",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Pays-Bas",
    "Pérou",
    "Philippines",
    "Pologne",
    "Polynésie française",
    "Porto Rico",
    "Portugal",
    "Qatar",
    "République centrafricaine",
    "République démocratique du Congo",
    "République dominicaine",
    "République tchèque",
    "Réunion",
    "Roumanie",
    "Royaume-Uni",
    "Russie",
    "Rwanda",
    "Sahara occidental",
    "Saint-Barthélemy",
    "Saint-Christophe-et-Niévès",
    "Saint-Marin",
    "Saint-Martin (partie française)",
    "Saint-Martin (partie néerlandaise)",
    "Saint-Pierre-et-Miquelon",
    "Saint-Siège",
    "Saint-Vincent-et-les-Grenadines",
    "Sainte-Hélène, Ascension et Tristan da Cunha",
    "Sainte-Lucie",
    "Samoa",
    "Samoa américaines",
    "Sao Tomé-et-Principe",
    "Sénégal",
    "Serbie",
    "Seychelles",
    "Sierra Leone",
    "Singapour",
    "Sint Maarten",
    "Slovaquie",
    "Slovénie",
    "Somalie",
    "Soudan",
    "Soudan du Sud",
    "Sri Lanka",
    "Suède",
    "Suisse",
    "Suriname",
    "Syrie",
    "Taïwan",
    "Tadjikistan",
    "Tanzanie",
    "Tchad",
    "Territoire britannique de l'océan Indien",
    "Terres australes françaises",
    "Thaïlande",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinité-et-Tobago",
    "Tunisie",
    "Turkménistan",
    "Turquie",
    "Tuvalu",
    "Ukraine",
    "Uruguay",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Wallis-et-Futuna",
    "Yémen",
    "Zambie",
    "Zimbabwe",
)

WORLD_COUNTRY_CHOICES = tuple(
    (name, name) for name in sorted(set(WORLD_COUNTRY_NAMES), key=lambda value: value.casefold())
)
WORLD_COUNTRY_VALUES = frozenset(name for name, _label in WORLD_COUNTRY_CHOICES)


def build_country_choices(selected_value: str = "", *, include_blank: bool = False):
    choices = list(WORLD_COUNTRY_CHOICES)
    normalized_value = (selected_value or "").strip()
    if normalized_value and normalized_value not in WORLD_COUNTRY_VALUES:
        choices.insert(0, (normalized_value, normalized_value))
    if include_blank:
        choices.insert(0, ("", "---------"))
    return tuple(choices)


def is_known_country(value: str) -> bool:
    return (value or "").strip() in WORLD_COUNTRY_VALUES
