"""WMS model facade.

Model classes are defined in `wms.models_domain` modules grouped by business aggregates.
This file keeps backward compatibility for existing imports (`from wms.models import ...`).
"""

from django.db import IntegrityError, connection, transaction
from django.db.models.functions import Length
from django.utils import timezone

from . import reference_sequences
from .document_scan import DocumentScanStatus
from .models_domain.billing import (
    AssociationBillingChangeRequest,
    AssociationBillingChangeRequestStatus,
    AssociationBillingFrequency,
    AssociationBillingGroupingMode,
    AssociationBillingProfile,
    BillingAssociationPriceOverride,
    BillingBaseUnitSource,
    BillingComputationProfile,
    BillingDocument,
    BillingDocumentCorrectionState,
    BillingDocumentKind,
    BillingDocumentLine,
    BillingDocumentReceipt,
    BillingDocumentShipment,
    BillingDocumentStatus,
    BillingExtraUnitMode,
    BillingIssue,
    BillingIssueStatus,
    BillingPayment,
    BillingPaymentMethod,
    BillingServiceCatalogItem,
    ReceiptShipmentAllocation,
)
from .models_domain.catalog import Product, ProductCategory, ProductKitItem, ProductTag
from .models_domain.equivalence import ShipmentUnitEquivalenceRule
from .models_domain.integration import (
    IntegrationDirection,
    IntegrationEvent,
    IntegrationStatus,
    WmsChange,
    WmsRuntimeSettings,
    WmsRuntimeSettingsAudit,
)
from .models_domain.inventory import (
    CartonSequence,
    Destination,
    Location,
    ProductLot,
    ProductLotStatus,
    RackColor,
    Receipt,
    ReceiptDonorSequence,
    ReceiptHorsFormat,
    ReceiptLine,
    ReceiptSequence,
    ReceiptStatus,
    ReceiptType,
    ShipmentSequence,
    Warehouse,
)
from .models_domain.planning import (
    CommunicationChannel,
    CommunicationDraft,
    CommunicationDraftStatus,
    CommunicationFamily,
    CommunicationTemplate,
    Flight,
    FlightSourceBatch,
    FlightSourceBatchStatus,
    PlanningArtifact,
    PlanningAssignment,
    PlanningAssignmentSource,
    PlanningDestinationRule,
    PlanningFlightSnapshot,
    PlanningIssue,
    PlanningIssueSeverity,
    PlanningParameterSet,
    PlanningParameterSetStatus,
    PlanningRun,
    PlanningRunFlightMode,
    PlanningRunStatus,
    PlanningShipmentSnapshot,
    PlanningVersion,
    PlanningVersionStatus,
    PlanningVolunteerSnapshot,
)
from .models_domain.portal import (
    AccountDocument,
    AccountDocumentType,
    AssociationContactTitle,
    AssociationPortalContact,
    AssociationProfile,
    AssociationRecipient,
    ComplianceOverride,
    ContactSubscription,
    DestinationCorrespondentDefault,
    DestinationCorrespondentOverride,
    DocumentRequirementTemplate,
    DocumentReviewStatus,
    NotificationChannel,
    Order,
    OrderDocument,
    OrderDocumentType,
    OrderLine,
    OrderReservation,
    OrderReviewStatus,
    OrderStatus,
    OrganizationContact,
    OrganizationRole,
    OrganizationRoleAssignment,
    OrganizationRoleContact,
    OrganizationRoleDocument,
    PublicAccountRequest,
    PublicAccountRequestStatus,
    PublicAccountRequestType,
    PublicOrderLink,
    RecipientBinding,
    RoleEventPolicy,
    RoleEventType,
    ShipperScope,
)
from .models_domain.shipment import (
    TEMP_SHIPMENT_REFERENCE_PREFIX,
    Carton,
    CartonFormat,
    CartonItem,
    CartonStatus,
    CartonStatusEvent,
    Document,
    DocumentType,
    GeneratedPrintArtifact,
    GeneratedPrintArtifactItem,
    GeneratedPrintArtifactStatus,
    MovementType,
    PrintCellMapping,
    PrintPack,
    PrintPackDocument,
    PrintPackDocumentVersion,
    PrintPackDocumentVersionChangeType,
    PrintPageFormat,
    PrintTemplate,
    PrintTemplateVersion,
    Shipment,
    ShipmentStatus,
    ShipmentTrackingEvent,
    ShipmentTrackingStatus,
    StockMovement,
)
from .models_domain.shipment_parties import (
    ShipmentAuthorizedRecipientContact,
    ShipmentRecipientContact,
    ShipmentRecipientOrganization,
    ShipmentShipper,
    ShipmentShipperRecipientLink,
    ShipmentValidationStatus,
)
from .models_domain.volunteer import (
    VolunteerAccountRequest,
    VolunteerAccountRequestStatus,
    VolunteerAvailability,
    VolunteerConstraint,
    VolunteerProfile,
    VolunteerUnavailability,
)

RECEIPT_REFERENCE_RE = reference_sequences.RECEIPT_REFERENCE_RE
normalize_reference_fragment = reference_sequences.normalize_reference_fragment


def generate_receipt_reference(*, received_on=None, source_contact=None) -> str:
    return reference_sequences.generate_receipt_reference(
        received_on=received_on,
        source_contact=source_contact,
        receipt_model=Receipt,
        receipt_sequence_model=ReceiptSequence,
        receipt_donor_sequence_model=ReceiptDonorSequence,
        transaction_module=transaction,
        connection_obj=connection,
        integrity_error=IntegrityError,
        receipt_reference_re=RECEIPT_REFERENCE_RE,
        localdate_fn=timezone.localdate,
    )


def generate_shipment_reference() -> str:
    return reference_sequences.generate_shipment_reference(
        shipment_model=Shipment,
        shipment_sequence_model=ShipmentSequence,
        transaction_module=transaction,
        connection_obj=connection,
        integrity_error=IntegrityError,
        length_cls=Length,
        localdate_fn=timezone.localdate,
    )


__all__ = [
    "AssociationBillingFrequency",
    "AssociationBillingGroupingMode",
    "AssociationBillingChangeRequestStatus",
    "BillingBaseUnitSource",
    "BillingExtraUnitMode",
    "BillingDocumentKind",
    "BillingDocumentStatus",
    "BillingDocumentCorrectionState",
    "BillingPaymentMethod",
    "BillingIssueStatus",
    "AssociationBillingProfile",
    "AssociationBillingChangeRequest",
    "BillingComputationProfile",
    "BillingServiceCatalogItem",
    "ShipmentUnitEquivalenceRule",
    "BillingAssociationPriceOverride",
    "ReceiptShipmentAllocation",
    "BillingDocument",
    "BillingDocumentShipment",
    "BillingDocumentReceipt",
    "BillingDocumentLine",
    "BillingPayment",
    "BillingIssue",
    "ProductCategory",
    "ProductTag",
    "Product",
    "ProductKitItem",
    "Warehouse",
    "Location",
    "RackColor",
    "CartonSequence",
    "ProductLotStatus",
    "ProductLot",
    "ReceiptType",
    "ReceiptStatus",
    "Receipt",
    "ReceiptLine",
    "ReceiptHorsFormat",
    "ReceiptSequence",
    "ReceiptDonorSequence",
    "ShipmentSequence",
    "Destination",
    "ShipmentStatus",
    "TEMP_SHIPMENT_REFERENCE_PREFIX",
    "Shipment",
    "ShipmentTrackingStatus",
    "ShipmentTrackingEvent",
    "OrderStatus",
    "OrderReviewStatus",
    "Order",
    "PublicOrderLink",
    "PublicAccountRequestStatus",
    "PublicAccountRequestType",
    "PublicAccountRequest",
    "AssociationProfile",
    "AssociationContactTitle",
    "AssociationPortalContact",
    "AssociationRecipient",
    "DestinationCorrespondentDefault",
    "DestinationCorrespondentOverride",
    "RoleEventType",
    "RoleEventPolicy",
    "NotificationChannel",
    "ContactSubscription",
    "DocumentRequirementTemplate",
    "OrganizationRoleDocument",
    "ComplianceOverride",
    "OrganizationRole",
    "OrganizationRoleAssignment",
    "OrganizationContact",
    "OrganizationRoleContact",
    "ShipperScope",
    "RecipientBinding",
    "ShipmentValidationStatus",
    "ShipmentShipper",
    "ShipmentRecipientOrganization",
    "ShipmentRecipientContact",
    "ShipmentShipperRecipientLink",
    "ShipmentAuthorizedRecipientContact",
    "DocumentReviewStatus",
    "DocumentScanStatus",
    "PlanningParameterSetStatus",
    "FlightSourceBatchStatus",
    "PlanningRunFlightMode",
    "PlanningRunStatus",
    "PlanningIssueSeverity",
    "PlanningVersionStatus",
    "PlanningAssignmentSource",
    "CommunicationChannel",
    "CommunicationDraftStatus",
    "CommunicationFamily",
    "AccountDocumentType",
    "AccountDocument",
    "OrderLine",
    "OrderReservation",
    "OrderDocumentType",
    "OrderDocument",
    "CartonFormat",
    "CartonStatus",
    "Carton",
    "CartonStatusEvent",
    "CartonItem",
    "MovementType",
    "StockMovement",
    "DocumentType",
    "Document",
    "PrintPageFormat",
    "PrintPack",
    "PrintPackDocument",
    "PrintPackDocumentVersion",
    "PrintPackDocumentVersionChangeType",
    "PrintCellMapping",
    "GeneratedPrintArtifactStatus",
    "GeneratedPrintArtifact",
    "GeneratedPrintArtifactItem",
    "PrintTemplate",
    "PrintTemplateVersion",
    "WmsChange",
    "WmsRuntimeSettings",
    "WmsRuntimeSettingsAudit",
    "IntegrationDirection",
    "IntegrationStatus",
    "IntegrationEvent",
    "VolunteerAccountRequest",
    "VolunteerAccountRequestStatus",
    "VolunteerAvailability",
    "VolunteerConstraint",
    "VolunteerProfile",
    "VolunteerUnavailability",
    "PlanningParameterSet",
    "PlanningDestinationRule",
    "FlightSourceBatch",
    "Flight",
    "PlanningRun",
    "PlanningIssue",
    "PlanningShipmentSnapshot",
    "PlanningVolunteerSnapshot",
    "PlanningFlightSnapshot",
    "PlanningVersion",
    "PlanningAssignment",
    "PlanningArtifact",
    "CommunicationTemplate",
    "CommunicationDraft",
    "RECEIPT_REFERENCE_RE",
    "normalize_reference_fragment",
    "generate_receipt_reference",
    "generate_shipment_reference",
]
